[package]
name = "cross_chain"
type = "contract"
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.3", directory = "noir-projects/aztec-nr/aztec" }
wormhole = { git = "https://github.com/NethermindEth/wormhole", tag = "v3.0.0", directory = "aztec/contracts" }
schnorr = { tag = "v0.1.3", git = "https://github.com/noir-lang/schnorr" }
compressed_string = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.3", directory = "noir-projects/aztec-nr/compressed-string" }

value_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.3", directory = "noir-projects/aztec-nr/value-note" }
address_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.3", directory = "noir-projects/aztec-nr/address-note" }
protocol_types = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.3", directory = "noir-projects/noir-protocol-circuits/crates/types" }
